### PR TITLE
Question update without page reload using AJAX

### LINKED ISSUE #7: Update question without page loading
## Explanation
After successfully attempting first question update next question without page loading using Ajax.

### PR DESCRIPTION
**Pull request by SubhradeepSS**
**Issue fixed: #7** 

**Features added:**

- automatic question update using ajax

- handling edge cases - submission before and after designated time (120 seconds)

**Note:**
removed the script reference to static `timer.js` and written all the javascript code inside `details.html` so as to use timer and ajax simultaneously.

### CODE REVIEW

**Comment by SubhradeepSS** [comment]
@todi-2000 I think this is an issue of **hard** level since the ajax part was required to be separately handled alongwith the timer :)
What is your opinion on it?

**Comment by SubhradeepSS** [comment]
@todi-2000 Can u please review my PR?

**Comment by SubhradeepSS** [comment]
@todi-2000 I think this is an issue of **hard** level :), since the ajax part was required to be simultaneously handled alongwith the timer.
What is your opinion on it?

**Comment by todi-2000** [comment]
> @todi-2000 I think this is an issue of **hard** level :), since the ajax part was required to be simultaneously handled alongwith the timer.
> What is your opinion on it?

Yes along with timer it is of hard level.Don't worry I will update and allocate you points considering it of hard level

**Comment by todi-2000** [comment]
It looks nice to me.

**Pull request merged**
